### ISSUE TITLE
Design Oberfläche SmartWatch

### ISSUE THREAD

**Issue by thorstenwitt** [thorstenwitt/mensaApp#10]
Als Nutzer möchte ich eine ansprechende SmartWatch-Oberfläche haben

**Comment by schwarzsascha** [comment]
- prüfen welche UIelemente für Androidsmartwatches existieren
- Design der Oberfläche auf dem "Papier"

**Comment by StevKanne** [comment]
- Auswahl von Tool: Balsamiq Mockups 3

-  Erster Entwurf angefertigt (In der Google Drive als Bild im Ordner "Design" abgelegt)

**Comment by StevKanne** [comment]
Design vorgestellt und Änderungen besprochen.
Rundes Design muss noch hinzugefügt werden und mit square übereinstimmen.

**Comment by StevKanne** [comment]
Action Buttons für "Datum" und "Phone App öffnen" hinzufügen.

**Comment by thorstenwitt** [comment]
Der Button zum öffnen der Phone App wird nur bei Benachrichtigungen verwendet.
Ich werde aber einen Button zur Datumsauswahl implementieren

**Comment by thorstenwitt** [comment]
Datumsauswahl ist implementiert. Die Anbindung zur Datenschnittstelle fehlt noch.
Muss ich erst mit Robert absprechen, was da jetzt passiert

**Comment by thorstenwitt** [comment]
Design ist umgesetzt

**Comment by karstchristopher** [comment]
Design überzeugt mit funktionaler Schlichtheit. 
Wenn der Name eines Gerichtes so lang ist, dass er in drei Zeilen umgebrochen wird, erscheint die dritte Zeile auf der SquareWatch nur noch zu Hälfte. Ist aber nicht wirklich störend.
