### ISSUE TITLE
Google-Store-Richtlinien

### ISSUE THREAD

**Issue by thorstenwitt** [thorstenwitt/mensaApp#14]
Als Projektmitglied möchte ich mich in die Google-Store-Richtlinien einarbeiten

**Comment by schwarzsascha** [comment]
checkliste -> welche richtlinien exitieren
was ist notwendig um die app in den store zu deployen 
(alpha beta etc.)

**Comment by schwarzsascha** [comment]
[links im wiki eingefügt](https://github.com/thorstenwitt/mensaApp/wiki/Links-zu-Google-Store-Richtlinien-und-Linzenzen) 
martial design, checklisten -> launch & localisation

**Comment by schwarzsascha** [comment]
Alpha-/Betatest einrichten

**Comment by schwarzsascha** [comment]
Auf offenen Beta-Test umgestellt.
Durch Link für alle erreichbar
