### ISSUE TITLE
Rechtliche Aspekte

### ISSUE THREAD

**Issue by thorstenwitt** [thorstenwitt/mensaApp#15]
Als Projektmanager möchte ich rechtlich abgesichert sein
- Fremddatennutzung
- Lizenzen
- Richtlinien
- ToS
- Finanzamt

**Comment by IzzySoft** [comment]
> - Lizenzen

Guter Punkt. Unter welcher Lizenz steht denn die App selbst? Die Angabe fehlt irgendwie :)

**Comment by robbirob** [comment]
Das ist tatsächlich diskussionswürdig.

**Comment by IzzySoft** [comment]
Und hat u.a. Einfluss auf:
- Fremddatennutzung (wie andere Apps/Dienste Eure Daten nutzen dürfen)
- Richtlinien (analog, aber auch zur Nutzung Eures hier auf Github gehosteten Codes)
- ToS (zumindest am Rand)
- ggf sogar "Finanzamt", da die passende Lizenz eine gewisse Art von "Gemeinnutz" bzw. zumindest "fehlende Gewinnorientiertheit" (aka "neutral zu behandeln") indizieren kann

Letzteres ist allerdings nur eine Vermutung meinerseits. Ich bin kein "Rechtsexperte" :)

**Comment by StevKanne** [comment]
Kurzzammenfassung rechtlicher Aspekte:
1. Fremddatennutzung: Mensadaten vom Studentenwerk Greifswald mit Nutzungserlaubnis. Code darf nur nach Freigabe weiter verwendet werden.
2. Lizenzen: GPLv3 → Open-Source + strenges Copyleft
3. Richtlinien: Richtlinien entsprechen Google Play für Entwickler, Github und Android Studio.
4. ToS: Nicht unbedingt nötig.
5. Finanzamt: Finanzamt spielt keine Rolle aufgrund kostenfreier App.
6. Berechtigungen: Netzwerkzugriff und -abruf.

Eine ausführlichere Version ist im Wiki hinterlegt. --> [Link](https://github.com/thorstenwitt/mensaApp/wiki/Rechtliche-Aspekte-%2315---Zusammenfassung)

**Comment by IzzySoft** [comment]
Hinweis:

> Zudem kann der Google Play Lizenzierungsservice bei Anfragen genutzt werden um so eine Übersicht der eigenen Lizenzen zu haben.

Damit werden alle Anwender ausgeschlossen, welche die *Google Play Store* App nicht nutzen wollen oder können (Stichwort: "Android ohne Google"). Die App sollte dies also, wenn überhaupt, nur optional nutzen – und nicht die Arbeit verweigern, wenn ein Zugriff hier fehlschlägt. Davon abgesehen sieht die hierfür benötigte Berechtigung (`vending.CHECK_LICENSE`) bei einer freien/gratis App immer etwas seltsam aus :)
