### ISSUE TITLE
App Store(s)

### ISSUE THREAD

**Issue by thorstenwitt** [thorstenwitt/mensaApp#16]
Als Projektmanager möchte ich den Bekanntheitsgrad erhöhen
- Maßnahmen zur Steigerung der App-Downloads bei Google Play
- App Store Optimierung -> Steigerung der Popularität

**Comment by schwarzsascha** [comment]
- Brandingeffekte

**Comment by schwarzsascha** [comment]
- "nur" play.google.com/store ?
- alternative stores? amazon, f-droid.org
- verteilung per webseite oder email

**Comment by schwarzsascha** [comment]
https://support.google.com/googleplay/android-developer/answer/4448378?hl=de
