### ISSUE TITLE
Softwarearchitekur -> Datansychronisierungs-Modul

### ISSUE THREAD

**Issue by thorstenwitt** [thorstenwitt/mensaApp#20]
Softwarearchitekur evaluieren, für das Datansychronisierungs-Modul zw. SmartWatch undSmartPhone

**Comment by robbirob** [comment]
[Linksammlung](https://github.com/thorstenwitt/mensaApp/wiki/Linksammlung-Android)

**Comment by robbirob** [comment]
Die Wearable-APK wird im Endeffekt später in die MensaApp gepackt und über diese deployed, man darf hierbei nicht vergessen, dass es sich dennoch um 2 verschiedene Anwendungen handelt , welche in der Entwicklungsphase auch so behandelt werden sollten. Code-Redundanzen sollten also, wie bei _normalen_ Java-Anwendungen auch, mit Hilfe von eigenen Bibliotheken gelöst werden.
Im Falle des Data-Sync-Modules sehe ich allerdings keinen Handlungsbedarf, da sich Redundanzen hier auf ein paar _@Override_-Methoden beschränken und wir zum jetzigen Zeitpunkt nicht sicher sein können, ob dort nicht doch Anpassungen nötig sind.
Siehe [Syncing Data Items](https://developer.android.com/training/wearables/data-layer/data-items.html)
