### ISSUE TITLE
Entwicklungsumgebung

### ISSUE THREAD

**Issue by thorstenwitt** [thorstenwitt/mensaApp#24]
Erstellung einer Entwicklungsumgebung für die Entwickler des MensaApp-Teams

**Comment by IzzySoft** [comment]
Prüft doch bitte in diesem Zusammenhang auch einmal Eure derzeitige Umgebung (siehe [hier](http://stackoverflow.com/q/40108130/2533433)). Eure letzte Release (v1.1) hat da [ein kleines Problem](https://www.virustotal.com/de/file/a4900a989fa9aae7ece9a5c1d7bac3aed81c3bc9aad57b498f87bf6c37d38f21/analysis/1479593583/). Ich werde sie daher zwischenzeitlich [in meinem Repo](https://apt.izzysoft.de/fdroid/index/apk/de.thorstenwitt.mensaapp) zumindest deaktivieren müssen.

**Comment by thorstenwitt** [comment]
Hi izzy,
danke für den Hinweis.
Ich hab den Build von gestern mal durch den Virenscanner prüfen lassen und da war alles roger. [siehe link](https://www.virustotal.com/de/file/e2d2cd6ef6e9e2d39e44031ea294245fb2d09aaeadadcc9d0d486d2b54fcb7ce/analysis/1479665032/). Kannst du uns ein bisschen auf die Sprünge helfen bei dem Problem. Liegt das an den Gradle Build Tools oder AndroidStudio oder am verwendeten SDK?

**Comment by IzzySoft** [comment]
Hi Thorsten,

leider weiß ich auch nicht mehr, als ich schon geschrieben habe. Habe lediglich die "roten Zeilen" durch die Suchmaschine gejagt und geschaut, welche Anhaltspunkte sich finden lassen. Dem [ersten Link](http://stackoverflow.com/q/40108130/2533433) zufolge könnte die Ursache in "Android studio and SDK" liegen, und wäre dann durch eine entsprechende Aktualisierung erledigt (die wahrscheinlich bei Euch bereits stattgefunden hat).

Leider finde ich bei Euch jetzt die APK Dateien gar nicht mehr (`https://github.com/thorstenwitt/mensaApp/tree/master/build` habt Ihr wohl entfernt?), daher kann ich die "kaputte" Version auch nicht austauschen. Wollt Ihr die APKs nicht mehr bei Github bereitstellen? Dann müsste ich die App ganz aus meinem Repo nehmen, da ich sie nicht mehr aktualisieren kann.

Falls Ihr sie hier doch bereithalten wollt, würde ich folgendes empfehlen:
- immer, wenn ein "stabiler Stand" erreicht ist (den Ihr freigeben wollt), erzeugt einen "tag". Der taucht dann automatisch unter `releases/` bei Github auf.
- Dort hängt Ihr dann auch das `.apk` ran, siehe [Creating Releases](https://help.github.com/articles/creating-releases/)

Ist kaum Aufwand. Mein Updater könnte das `.apk` dann von dort automatisch aufgreifen.

**Comment by thorstenwitt** [comment]
Hallo Izzy,

ja wir hatten das APK nach deiner Virenmeldung erstmal rausgeschmissen.
Danke für deinen Hinweis :)
Ich hab unter Releases eine APK abgelegt.

**Comment by IzzySoft** [comment]
Gerade gezogen und ins Repo gepackt (alte Version gelöscht). Clean :) Danke! Geht damit sogleich wieder online. Ihr könnt daher jetzt gern für den Download via F-Droid App [hierher](https://apt.izzysoft.de/fdroid/index/apk/de.thorstenwitt.mensaapp) verweisen.

**Comment by thorstenwitt** [comment]
Erledigt :)
