### ISSUE TITLE
Einarbeitung in Datenschnittstelle vom Studentenwerk

### ISSUE THREAD

**Issue by StevKanne** [thorstenwitt/mensaApp#26]

**Comment by thorstenwitt** [comment]
andere App-Projekte greifen die Daten direkt aus den HTML-Dateien ab.

In Neubrandenburg gibt es auch ein ähnliches Projekt und dort werden
XML-Datei zur Verfügung gestellt. Der Aufruf erfolgt über die URL:
http://studwerk.fh-stralsund.de/speiseplan/speiseplan_xml.php

Diese Datei enthält die Daten unserer vier Standorte:

Mensa am Wall, Greifswald

Mensa am Bertholdt-Beitz-Platz, Greifswald

Mensa Stralsund

Mensa Neubrandenburg

Das Schema dahinter basiert auf einer überholten Anforderung einer
„kommerziellen“ App, welche aber nie endgültig umgesetzt wurde.

Eine Aktualisierung der Speiseplan-Daten erfolgt bei uns wie folgt:

·         Alle 5 Minuten gibt es einen Datenexport von der
Warenwirtschaft mit anschließender Übertragung auf den Web-Server.

·         Der Web-Server liest alle 3 Minuten die Exportdaten ein.

·         Mittels einer Verwaltungsoberfläche können die Mitarbeiter
sekundengenau die Ausgabe beeinflussen (z.B. Angebote ausblenden, wenn
diese ausverkauft sind).

**Comment by StevKanne** [comment]
Anfrage wegen MensaVital in neuen Epic #36  verschoben

**Comment by thorstenwitt** [comment]
Das XML auf der Seite ist invalide. Wir könnten es trotzdem mit Hilfe von JSoup parsen. 
Aber evtl. sollten wir auch das Studentenwerk mal diesbezüglich ansprechen.

**Comment by thorstenwitt** [comment]
Robert teilt nun meine Ansicht, dass aufgrund der Verwendung des "Kaufmännischen Unds". Das XML nicht mehr well-formed ist.

http://stackoverflow.com/questions/8770097/how-to-make-saxparser-ignore-escape-codes
