### ISSUE TITLE
DevVM

### ISSUE THREAD

**Issue by thorstenwitt** [thorstenwitt/mensaApp#3]
Als Entwickler möchte ich eine DevVM benutzen
- Recherche
- Aufsetzen
- Testen
- Verteilen

**Comment by thorstenwitt** [comment]
DevVM muss noch auf das Github-Repository umgestellt werden

**Comment by thorstenwitt** [comment]
DEV-VM wurde per USB-Stick an Robert und Christopher übertragen.
Bitte gebt mal Feedback ob alles läuft!

**Comment by robbirob** [comment]
Die Emulatoren funktionieren beide nicht in der vm. Ich werde am Wochenende noch 1h debugging betreiben und morgen nochmal auf dem Firmen-Laptop testen.

**Comment by thorstenwitt** [comment]
Hallo robbirob, startest du die emulatoren über Android-Studio? Da gibt es ein Problem, weil beim Starten des Emulators noch nen Parameter mitgeben muss, damit er die Systemlibs von g++ oder so verwendet. Probiere mal bitte die Shellskripte auf dem Desktop aus zum Starten der Emulatoren

**Comment by robbirob** [comment]
Ich habe beide Varianten probiert. Ja, ist mir auch aufgefallen. Die angelegten Startskripte habe ich gestern Nacht mehrfach probiert. Ich bekomme hier zwar keine offensichtlichen Fehlermeldungen, als ich nach 1,5h allerdings immernoch im "Android"-Bootlogo klebte, bin ich dann ins bett gegangen.  Hier also auch keine erfolge. Wie gesagt, ich werde noch maximal 1h Stunde in Fehlersuche investieren + morgen nochmal auf dem Lappi. Wenn das alles nichts bringt werde ich auf andere Lösungen umsteigen, d.h. zumindest die Emus auf dem Hostsystem laufen lassen. Zudem müssten wir evtl die Systempartition vergrößern, ich bekam gestern meldungen, das die Platte voll ist. Die Meldung erholt sich zwar nach reboot, es dauert aber nicht lange unter benutzung von Android-Studio, da ist sie wieder voll. Diese Android-Subsystem und SDKs sind alle riesig.

**Comment by karstchristopher** [comment]
In meiner VM laufen phone und watch Emulator ohne Probleme (starten auch in akzeptabler Zeit). Das die beim Booten hängen bleiben kenne ich aber von meinem anderen System mit wenig Arbeitsspeicher auch. 
Aso wegen des knappen Platzes auf der Platte habe ich auch gerade ein Meldung bekommen.

**Comment by robbirob** [comment]
Einen Workaround für das kleine Problem mit der Auflösung gibt es [hier](http://askubuntu.com/questions/251375/cant-get-1920-x-1080-in-ubuntu-via-vmware#556836).

**Comment by robbirob** [comment]
Also es liegt an meiner uralten AMD CPU. Ich werde auf den Laptop entwickeln. Ticket wird geschlossen
