### ISSUE TITLE
Refactoring Klassennamen und Methodenbezeichnungen

### ISSUE THREAD

**Issue by thorstenwitt** [thorstenwitt/mensaApp#34]

**Comment by thorstenwitt** [comment]
Klassennamen in Einzahl, Bezeichnungen auf Deutsch

**Comment by thorstenwitt** [comment]
In Neubrandenburg gibt es auch ein ähnliches Projekt und dort werden
XML-Datei zur Verfügung gestellt. Der Aufruf erfolgt über die URL:
http://studwerk.fh-stralsund.de/speiseplan/speiseplan_xml.php

Diese Datei enthält die Daten unserer vier Standorte:

Mensa am Wall, Greifswald

Mensa am Bertholdt-Beitz-Platz, Greifswald

Mensa Stralsund

Mensa Neubrandenburg

Das Schema dahinter basiert auf einer überholten Anforderung einer
„kommerziellen“ App, welche aber nie endgültig umgesetzt wurde.

Eine Aktualisierung der Speiseplan-Daten erfolgt bei uns wie folgt:

·         Alle 5 Minuten gibt es einen Datenexport von der
Warenwirtschaft mit anschließender Übertragung auf den Web-Server.

·         Der Web-Server liest alle 3 Minuten die Exportdaten ein.

·         Mittels einer Verwaltungsoberfläche können die Mitarbeiter
sekundengenau die Ausgabe beeinflussen (z.B. Angebote ausblenden, wenn
diese ausverkauft sind).

**Comment by karstchristopher** [comment]
Im Zuge des Refactoring wurden bisher:
- Klassennamen in Einzahl geändert,
- Klassennamen, Methoden und Variablen ins Englische übersetzt,
- zur Strukturierung der Klassen wurden Pakete angelegt und Getter und Setter erfasst,
- und der Code um ungenutzte Methoden bereinigt.

**Comment by thorstenwitt** [comment]
getGerichte !!!
