### ISSUE TITLE
MensaVital bewerben

### ISSUE THREAD

**Issue by StevKanne** [thorstenwitt/mensaApp#36]
Informationen zu MensaVital in die App einbinden um diese stärker zu bewerben.

Anfrage kam direkt vom Studentenwerk.

Entscheidung, ob wir dies implementieren noch offen!

**Comment by StevKanne** [comment]
...
heute hat wieder der Mensaausschuss diesmal in Stralsund getagt. Von Seiten der Stralsunder Mitglieder war der Wunsch geäußert worden die Menülinie mensaVital stärker zu bewerben. Wäre es möglich, dass Sie Informationen über diese Marke mit in die App einbinden?

Nähere Informationen zur Menülinie finden Sie auf der Homepage unter: www.mensavital.de
...

**Comment by schwarzsascha** [comment]
- prüfen der Machbarkeit
- Ergebnis kommunizieren

**Comment by thorstenwitt** [comment]
Hallo,

dass MensaVital-Menü grün einzufärben ist auf jedenfall machbar.
Ich kann im MenuListAdapter eine Fallunterscheidung einbauen und wenn es sich um MensaVital handelt wird der Text grün gefärbt.

**Comment by StevKanne** [comment]
Studentenwerk informiert und aktuelle Mail an alle Teammitglieder weitergeleitet.
