### ISSUE TITLE
Google Spracherkennung Lizenzsituation

### ISSUE THREAD

**Issue by StevKanne** [thorstenwitt/mensaApp#37]
Lizenzfreiheit der Google Spracherkennung überprüfen

**Comment by StevKanne** [comment]
Nach bisherigen Untersuchungen scheint die Google Sprachsteuerung/Voice Actions lizenzfrei zu sein bzw. habe ich bisher keine Informationen diesbezüglich gefunden.

**Comment by robbirob** [comment]
@StevKanne 
Hier mal die allgemeinen ToS für Google-APIs, kannst ja da mal drüber schauen, ob was relevantes für uns drinne steht.
[https://developers.google.com/terms/](https://developers.google.com/terms/)
