### ISSUE TITLE
design der usability zur einstellung der hintergrundaktualisierung

### ISSUE THREAD

**Issue by schwarzsascha** [thorstenwitt/mensaApp#38]

**Comment by StevKanne** [comment]
Infos zu dem Hinzufügen/Behandeln eines Background Services unter folgendem Link:
[Running a Background Service](https://developer.android.com/training/run-background-service/index.html)

Auch im wiki hinterlegt.

**Comment by StevKanne** [comment]
Idee für Phone: Unter dem Reiter Einstellungen den Punkt "Hintergrundaktualisierung" als On/Off Button definieren oder wenn möglich einen festen Termin (z.B. täglich um 10 Uhr) definieren.

Idee für Watch: Als Action Button definieren, bei dem sich der Status von Hintergrundaktualisierung jedesmal ändert (also von "On" zu "Off" und andersherum).

Die Punkte wurden dem Design-Vorschlag hinzugefügt.

**Comment by StevKanne** [comment]
Thorsten für die Umsetzung hinzugefügt.

**Comment by thorstenwitt** [comment]
Für das Wintersemester wurde abgesprochen, dass nur noch getestet wird und bestehende Funktionen gehärtet.
