### ISSUE TITLE
Fehler beim laden der Mensadaten bei der Appwiederherstellung

### ISSUE THREAD

**Issue by schwarzsascha** [thorstenwitt/mensaApp#43]
- wenn die Mensapp geöffnet wurde anschließend der Homebutton gedrückt wurde, nach Zeit x die App wieder geöffnet wurde, werden "falsche" Preise angezeigt

**Comment by karstchristopher** [comment]
Den Zustand zu replizieren in dem der Fehler Auftritt ist schwieriger als gedacht, womit dann auch die Fehlersuche nicht so trivial wie angenommen ist. 
Nochmal zum Verständnis: Wenn die MensaApp etwa durch Betätigung des Home-Button in den Zustand onPause oder onStop versetzt wird und in diesem Zuge die Instanz der Sitzung gespeichert wird, kommt es nach einer Zeit X beim recreating der Aktivity dazu, dass immer auf die Preiskategorie für Gäste referenziert wird.
Folgendes Vorgehen: Die Suche nach dem Fehler wird weiter forciert wobei ich gerne auf die Expertise des Architekten der App zurückgreifen würde, um möglichst schnell eine Lsg. zu finden.

**Comment by thorstenwitt** [comment]
Ich habe jetzt einen Tipp auf Stackoverflow bekommen. Ich muss die Floats in gleicher Reihenfolge lesen, wie ich sie auch geschrieben habe. Jetzt ist testen angesagt
