### ISSUE TITLE
Anzeige Mensadaten bei nicht deutscher Sprache des OS

### ISSUE THREAD

**Issue by schwarzsascha** [thorstenwitt/mensaApp#44]
ist die Sprache des Systems auf englisch, wird nur der aktuelle Tag angezeigt

**Comment by thorstenwitt** [comment]
Durch die neue XML-Schnittstelle dürfte der Fehler nicht mehr auftreten.
Ich habe aber noch eingebaut, dass er je nach Sprache das entsprechende Default-Datumsformat anzeigt.

**Comment by schwarzsascha** [comment]
- es werden jetzt auch bei englischer Sprache (OS) die Gerichte der laufenden Woche angezeigt
- das Datum wird im Format Nov 16, 2016 angezeigt
