### ISSUE TITLE
Ermitteln welche Lizenz wir verwenden.

### ISSUE THREAD

**Issue by StevKanne** [thorstenwitt/mensaApp#50]
GPL, MIT...

**Comment by schwarzsascha** [comment]
https://github.com/thorstenwitt/mensaApp/wiki/Lizenzen

**Comment by StevKanne** [comment]
Siehe: https://github.com/thorstenwitt/mensaApp/wiki/Links-zu-Google-Store-Richtlinien-und-Linzenzen

**Comment by StevKanne** [comment]
Lizenz wurde ermittelt --> GPLv3 
Alternative: BSD-Lizenz

Ausführlichere Informationen siehe #15 oder [Wiki - Punkt Lizenzen](https://github.com/thorstenwitt/mensaApp/wiki/Rechtliche-Aspekte-%2315---Zusammenfassung)
