### ISSUE TITLE
Einarbeitung Serializable

### ISSUE THREAD

**Issue by StevKanne** [thorstenwitt/mensaApp#52]

**Comment by robbirob** [comment]
http://stackoverflow.com/questions/25938273/can-i-send-custom-objects-to-android-wear

**Comment by robbirob** [comment]
Implementierung des Marshallings der Lunch-Objekte war erfolgreich.

Ich habe zur Zeit noch ein kleines Problemchen: Die onDataChanged() Methode wird nur aufgerufen wenn die Daten wirklich gechanged sind. Ich habe versucht zu tricksen und TimeStamps und Counter einzubauen, war aber noch nicht erfolgreich. Zur Zeit wird irgendwie immer nur das letze übertragene Element angezeigt. Kein Plan wieso. In der MenuActivity des Mobile-Moduls sind mehrer Sendungen zu finden, hier kann man sehen wie man es benutzen kann. Ich würde mich da sehr gerne nochmal mit Thorsten gemeinsam ransetzten. Um dem Problem auf die schliche zu kommen.
