### ISSUE TITLE
Grünfärbung von MensaVital in Watch-App implementieren

### ISSUE THREAD

**Issue by thorstenwitt** [thorstenwitt/mensaApp#61]

**Comment by thorstenwitt** [comment]
Damit ich das auf der Watch-Seite umsetzen kann müsste ich erstmal von Robert wissen ob wir jetzt Objekte schicken oder Strings

**Comment by robbirob** [comment]
Wir schicken Lunch-Objekte

**Comment by thorstenwitt** [comment]
Grünfärbung in der WatchApp implementiert
