### ISSUE TITLE
Optimierung Kommunikation Uhr-Phone

### ISSUE THREAD

**Issue by robbirob** [thorstenwitt/mensaApp#62]
Uhr muss Daten holen, ohne das auf dem Phone eine Interaktion ausgelöst wurde

**Comment by thorstenwitt** [comment]
Uhr holt sich Daten sobald, der Connect ausgeführt wurde.
Die Frage ist nur offen, was bei einer Neuinstallation passiert und wenn zuerst die Uhr-App gestartet wird.
Wir müssten versuchen die App auf dem Phone denn zum Start zu triggern

**Comment by thorstenwitt** [comment]
Uhr triggert Start der Phone-App wenn noch keine Daten vorhanden sind.
