### ISSUE TITLE
Umstellung auf aktuelle API

### ISSUE THREAD

**Issue by robbirob** [thorstenwitt/mensaApp#63]
Follow the Android Wear 2.0 App Distribution documentation to update your app. Key steps are listed below:

1.  API level: Set your APKs to minSdkVersion 23 or higher and use the runtime permissions model.
2.    Android Wear 2.0 targeting: Target your APKs to watches by requiring "android.hardware.type.watch" in the manifest.
3.    iOS support: Specify whether your APKs are standalone and can run on watches paired to iPhones. You can test using the latest Android Wear app for iOS.
4.    App management: Upload your APKs via multi-APK using the Play Developer Console.

**Comment by thorstenwitt** [comment]
Bei alten Uhren wird die App weiterhin unterstützt. Darauf liegt der Fokus
